
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: wh5268925
  resources:
    static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/